#!/bin/bash

USER='riley'
# change to your user-account

install_yay() {
    cd /tmp/ # Change Directory to Dedicated Temporary Directory
    git clone https://aur.archlinux.org/yay.git # Use git to clone yay from the AUR
    chown -R riley:riley /tmp/yay
    cd /tmp/yay # Change Directory to the new yay folder
    makepkg  
    su -c "pacman -U --noconfirm yay-*.tar.zst" root # use pacman to install yay (and yay-debug) without prompting for confirmations
    cd / # Change directory to root
    rm -rf /tmp/yay # Delete the yay/ directory from /tmp
}

install_flatpak() {
    su -c "pacman -S --noconfirm flatpak" root
}

install_system_packages() {
    local packages="" # Set a blank local variable that can be added to later.

    # Basic System-Wide Tools
    packages+=" xdg-user-dirs xdg-desktop-portal nano pacman-contrib cifs-utils gvfs gvfs-smb smbclient samba bluez ttf-win10 p7zip-gui nvidia-utils opencl-nvidia ffnvcodec-headers xdg-utils amd-ucode decklink hyfetch man-db ntfs-3g v4l2loopback-dkms vulkan-headers vulkan-icd-loader libadwaita adwaita-cursors breeze breeze-icons "

    # Desktop Utilities
    packages+=" gnome-calculator gnome-music gnome-disk-utility piper eog thunderbird vlc qbittorrent lutris "

    # Audio Software(s)
    packages+=" pipewire-alsa pipewire-audio pipewire-jack pipewire-pulse wireplumber reaper firefox "

    # Desktop / WM and Required Tools
    packages+=" xdg-desktop-portal-gtk xdg-desktop-portal-gnome gnome-desktop gdm gnome-system-monitor gnome-tweaks gnome-control-center gnome-keyring gnome-bluetooth nautilus xorg "

    su -c "pacman -S --noconfirm $packages" root
}

install_steam() {
    su -c "pacman -S --noconfirm steam" root
}

install_yay_packages() {
    local packages=""

    # Custom Desktop Utilities
    packages+=" gnome-terminal-transparency gnome-browser-connector "

    # Themes
    packages+=" adwaita-dark "

    # Games and Launchers
    packages+=" heroic-games-launcher minecraft-launcher pamac-flatpak "

    # Custom Packages
    packages+=" vscodium keepassxc obsidian goxlr-utility thorium-browser-bin obs-studio-git gpu-screen-recorder-git streamdeck-ui fontforge "
    
    su -c "yay -S --noconfirm $packages" $USER
    #bash --init-file <(echo ". \"$HOME/.bashrc\"; yay -S --noconfirm $packages") # Automatically Install listed packages without confirmation
}

install_annoying_yay_packages() {
    # Mostly installs that require manual intervention and or import of keys
    packages=""

    packages+=" spotify media-downloader "

    yay -S $packages
}

install_flatpak_packages() {
    flatpak install com.discordapp.Discord -y
}

setup_systemd() {
    su -c "systemctl enable gdm" root # Enable the Gnome Display Manager
    su -c "systemctl enable DesktopVideoHelper" root 
}

basic_configs() {
    su -c "cp -s /usr/bin/nano /usr/bin/vi" root #similar to ln, symlink nano to vi as default editor
}

cleanup() {
    su -c "pacman -Syu && paccache -rk1 && paccache -ruk0" root
    # Applies available updates and clears cached versions
    exit
}

if [ "$(id -u)" -eq 0 ]; then
    su -c './install' @USER
else
    install_yay && sleep 1 &&
    install_flatpak && sleep 1 &&
    install_system_packages && sleep 1 &&
    install_steam && sleep 1 &&
    install_yay_packages && sleep 1 &&
    install_flatpak_packages && sleep 1 &&
    setup_systemd && sleep 1 &&
    basic_configs && sleep 1 &&
    cleanup
fi
