#!/bin/bash

USER='riley'
# change to your user-account

install_yay() {
    cd /tmp/ # Change Directory to Dedicated Temporary Directory
    git clone https://aur.archlinux.org/yay.git # Use git to clone yay from the AUR
    chown -R riley:riley /tmp/yay
    cd /tmp/yay # Change Directory to the new yay folder
    su -c 'makepkg' $USER
## su - swich user
## -c - issue command(s)
## 'makepkg' - make the AUR package(s)
## $USER - Global Variable: User Account to be used
    
    pacman -U --noconfirm yay-*.tar.zst # use pacman to install yay (and yay-debug) without prompting for confirmations
    cd / # Change directory to root
    rm -rf /tmp/yay # Delete the yay/ directory from /tmp
}

install_flatpak() {
    pacman -S --noconfirm flatpak 
}

install_system_packages() {
    local packages="" # Set a blank local variable that can be added to later.

    # Basic System-Wide Tools
    packages+=" xdg-user-dirs xdg-desktop-portal nano pacman-contrib cifs-utils gvfs gvfs-smb smbclient samba bluez ttf-win10 p7zip-gui nvidia-utils opencl-nvidia ffnvcodec-headers xdg-utils amd-ucode decklink hyfetch man-db ntfs-3g v4l2loopback-dkms vulkan-headers vulkan-icd-loader libadwaita adwaita-cursors breeze breeze-icons "

    # Desktop Utilities
    packages+=" gnome-calculator gnome-music gnome-disk-utility piper eog thunderbird vlc qbittorrent lutris "

    # Audio Software(s)
    packages+=" pipewire-alsa pipewire-audio pipewire-jack pipewire-pulse wireplumber reaper firefox "

    # Desktop / WM and Required Tools
    packages+=" xdg-desktop-portal-gtk xdg-desktop-portal-gnome gnome-desktop gdm gnome-system-monitor gnome-tweaks gnome-control-center gnome-keyring gnome-bluetooth nautilus "

    pacman -S --noconfirm $packages
}

install_steam() {
    pacman -S --noconfirm steam
}

install_yay_packages() {
    local packages=""

    # Custom Desktop Utilities
    packages+=" gnome-terminal-transparency gnome-browser-connector "

    # Themes
    packages+=" adwaita-dark "

    # Games and Launchers
    packages+=" heroic-games-launcher minecraft-launcher pamac-flatpak "

    # Custom Packages
    packages+=" vscodium keepassxc obsidian goxlr-utility thorium-browser-bin spotify obs-studio-git gpu-screen-recorder-git media-downloader streamdeck-ui fontforge "
    
    yay -S --noconfirm $packages # Automatically Install listed packages without confirmation
}

install_flatpak_packages() {
    flatpak install com.discordapp.Discord -y
}

setup_systemd() {
    systemctl enable gdm.service # Enable the Gnome Display Manager
    systemctl enable DesktopVideoHelper.service
}

basic_configs() {
    cp -s /usr/bin/nano /usr/bin/vi #similar to ln, symlink nano to vi as default editor
}

cleanup() {
    sudo pacman -Syu && sudo paccache -rk1 && sudo paccache -ruk0
    # Applies available updates and clears cached versions
    exit
}

if [ "$(id -u)" -eq 0 ]; then
    su -c './install' @USER
else
    install_yay && sleep 1 &&
    install_flatpak && sleep 1 &&
    install_system_packages && sleep 1 &&
    install_steam && sleep 1 &&
    install_yay_packages && sleep 1 &&
    install_flatpak_packages && sleep 1 &&
    setup_systemd && sleep 1 &&
    basic_configs && sleep 1 &&
    cleanup
fi
